### ISSUE TITLE
error : No ad config

### ISSUE THREAD

**Issue by farzadkamali20** [amirisback/frogo-admob#25]
i do not change anything and i try to use test (demo). but show error.

Error - Run - IFrogoAdRewarded [callback] : onAdFailedToLoad()
Error - onAdFailedToLoad [code] : 3
Error - onAdFailedToLoad [domain] : com.google.android.gms.ads
Error - onAdFailedToLoad [message] : No ad config.

**Comment by amirisback** [comment]
thanks you for your report i will re check for find bug

**Comment by amirisback** [comment]
I added an initiation status from google admob so you can search to check whether you have initiated or not, and I've also added a log to get a Rewarded Unit Id
