### ISSUE TITLE
saving activity context is bad practice?

### ISSUE THREAD

**Issue by SodaSurfer** [amirisback/frogo-admob#71]
Hi there
I see that you save the activity context in the admob class and then use it to show interstitial ads.
isn't it a bad practice to save the activity context as a member variable?
wouldn't it be better practice to pass the activity context only when we want to show an interstitial ad?

**Comment by amirisback** [comment]
maybe u can give some suggestion on pull request, so we can discuss together thank you @SodaSurfer

**Comment by amirisback** [comment]
i think, if u didn't call any ad from admob u can override method ```setupMonetized()```
Sample : 
- Using Admob in CurrentActivity
```kotlin
    override fun setupMonetized() {
        super.setupMonetized()
    }
```

- Not Using Admob In CurrentActivity 
```kotlin
    override fun setupMonetized() {
        // delete super method, u also delete initial setup
    }
```

can we agree with this situation? @SodaSurfer

**Comment by amirisback** [comment]
thank you, for response if still not satisfied, please re open this issue
