### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by guozhiqiang123** [amirisback/frogo-admob#74]
Run this project,but crashed.
![image](https://github.com/amirisback/frogo-admob/assets/20378988/2636ef86-b28a-4d10-93d7-a43cb5359b3a)

**Comment by amirisback** [comment]
can u give me reproduce bug? in video or logcat?

**Comment by amirisback** [comment]
@guozhiqiang123

**Comment by guozhiqiang123** [comment]
I know why it crashed because my phone doesn't have Google Service.

**Comment by amirisback** [comment]
so can't u suggest how can i fix this?
