### ISSUE TITLE
ad listeners

### ISSUE THREAD

**Issue by Akin-junior** [amirisback/frogo-admob#8]
Hi, how can I use ad listeners(ad close listener) especially for rewarded ads. If I use After OnUserEarnedReward to intent other activity rewarded ad stays on in the background.  It can be a problem for both users and advertising policy.

**Comment by amirisback** [comment]
Thanks For your report, i will fix this problem as soon as posible

**Comment by amirisback** [comment]
sorry for waiting so long, you can enjoy this feature on 4.1.7 version thank you
