### ISSUE TITLE
Hope to increase the failure callback

### ISSUE THREAD

**Issue by southbaird** [amirisback/frogo-admob#9]
`setupShowAdsRewardedInterstitial(object : IFrogoAdmob.UserEarned {
                    override fun onUserEarnedReward(rewardItem: RewardItem) {
                        // TODO User Get Reward
                    }
                })`

**Comment by amirisback** [comment]
thanks for feature request, i will adding as soon as posible,

**Comment by amirisback** [comment]
sorry for waiting so long, you can enjoy this feature on 4.1.7 version thank you
